version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Building ledger-writer...
      - mvn clean package

artifacts:
  files:
    - target/ledger-writer-1.0.0.jar
    - template.yaml
  name: ledger-writer-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '/root/.m2/**/*'