version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo Building notification-service...
      - mvn clean package

artifacts:
  files:
    - target/notification-service-1.0.0.jar
    - template.yaml
  name: notification-service-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - '/root/.m2/**/*'
